### ISSUE TITLE
Grin Node is outdated (but I don't think it should be)

### ISSUE THREAD

**Issue by BarneyChambers** [vault713/wallet713#167]
I am currently running a Grin node version 2.0.0 (git v2.0.0) built for x86_64 by rust 1.35.0.

I am also running wallet713 v2.0.0-beta.1

When I attempt to run the wallet I get the error message:

`The Grin Node in use (version 1.x.x series) is outdated and incompatible with this wallet version. Please update the node to version 2.0.0 or later`

But I am running Grin node version 2.0.0, at least that's what it is telling me? I downloaded it from the releases github today (03/07/2019)

**Comment by jaspervdm** [comment]
By default wallet713 uses a node provided by vault713, which hasn't been updated to v2.0.0 yet because many users are still on v1.x. To use your own node, change in the config in `~/.wallet713/main/wallet713.toml` and add the following line:
```
grin_node_uri = "http://127.0.0.1:3413"
```
Or replace with the appropriate ip:port if you are running the node somewhere else than locally

**Comment by BarneyChambers** [comment]
> By default wallet713 uses a node provided by vault713, which hasn't been updated to v2.0.0 yet because many users are still on v1.x. To use your own node, change in the config in `~/.wallet713/main/wallet713.toml` and add the following line:
> 
> ```
> grin_node_uri = "http://127.0.0.1:3413"
> ```
> 
> Or replace with the appropriate ip:port if you are running the node somewhere else than locally

Worked a treat. Thanks, it would've taken me a long long time to figure that one out
